---
# defaults file for init
localhost_brew_packages:
  - bash-language-server
  - btop
  - colordiff
  - ctop
  - docker-compose
  - eza
  - ffmpeg
  - fish
  - fzf
  - git
  - glab
  - go
  - go-jira
  - gopls
  - hadolint
  - helm
  - htop
  - httpie
  - hugo
  - imagemagick
  - k9s
  - kubernetes-cli
  - logcli
  - lua-language-server
  - markdownlint-cli
  - ncdu
  - neofetch
  - neovim
  - nmap
  - nnn
  - openconnect
  - ossp-uuid
  - pandoc
  - pass
  - pastel
  - poppler
  - pueue
  - pyright
  - python@3.11
  - ripgrep
  - s3cmd
  - sevenzip
  - sshpass
  - tmux
  - watch
  - wget
  - wimlib
  - xray
  - yq
  - zoxide
  - zsh

localhost_brew_casks:
  - alt-tab
  - dbeaver-community
  - docker-desktop
  - duckduckgo
  - firefox
  - font-iosevka-nerd-font
  - font-iosevka-term-nerd-font
  - freelens
  - google-chrome
  - iterm2
  - jitsi-meet
  - libreoffice
  - lm-studio
  - monokle
  - obsidian
  - shotcut
  - shottr
  - telegram-desktop
  - thor
  - ticktick
  - transmission
  - utm
  - zoom

localhost_dotfiles:
  - .config/nvim/init.lua
  - .config/nvim/lua/lsp.lua  
  - .config/nvim/lua/mappings.lua  
  - .config/nvim/lua/markdown.lua  
  - .config/nvim/lua/options.lua  
  - .config/nvim/lua/plugins.lua  
  - .config/nvim/lua/statusline.lua  
  - .config/nvim/lua/telescope-zoxide.lua  
  - .config/nvim/lua/treesitter.lua
  - .config/fish/conf.d/aliases.fish
  - .config/fish/conf.d/functions.fish
  - .config/fish/conf.d/variables.fish
  - .tmux.conf

localhost_home_linux_spec:
  - .Xresources
  - .clang-format
  - .xinitrc
